-- 30 more Pokémon TCG cards
INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, ressistence, retreta, cardnumberincollection, collection_id, type_id, stage_id)
VALUES
(50, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'None', '1 Colorless', 45, 1, 1, 1),
(60, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'None', '2 Colorless', 54, 1, 1, 2),
(80, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', 'Fighting', '1 Colorless', 33, 1, 1, 3),
(40, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', 'None', '1 Colorless', 69, 1, 1, 1),
(60, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', '—', 'Fire', 'None', '2 Colorless', 33, 1, 1, 2),
(80, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', 'Fighting', '1 Colorless', 17, 1, 1, 3),
(50, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'None', '1 Colorless', 50, 1, 5, 1),
(60, 'Haunter', 'Gas Pokémon', 'Hypnosis', '—', 'Psychic', 'None', '1 Colorless', 29, 1, 5, 2),
(80, 'Gengar', 'Shadow Pokémon', 'Nightmare', '30', 'Psychic', 'None', '2 Colorless', 5, 1, 5, 3),
(40, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', 'None', '1 Colorless', 43, 1, 5, 1),
(60, 'Kadabra', 'Psi Pokémon', 'Recover', '—', 'Psychic', 'None', '2 Colorless', 32, 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', 'None', '3 Colorless', 1, 1, 5, 3),
(70, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', 'None', '1 Colorless', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', 'None', '2 Colorless', 34, 1, 6, 2),
(100, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', 'None', '3 Colorless', 8, 1, 6, 3),
(60, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', 'None', '1 Colorless', 58, 2, 1, 1),
(70, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', 'None', '2 Colorless', 38, 2, 1, 2),
(90, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', 'None', '2 Colorless', 13, 2, 1, 3),
(50, 'Eevee', 'Evolution Pokémon', 'Tackle', '10', 'Fighting', 'Psychic', '1 Colorless', 51, 2, 7, 1),
(70, 'Flareon', 'Flame Pokémon', 'Flamethrower', '50', 'Water', 'None', '2 Colorless', 3, 2, 2, 2),
(70, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Lightning', 'None', '2 Colorless', 12, 2, 3, 2),
(70, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', 'None', '1 Colorless', 4, 2, 4, 2),
(60, 'Zubat', 'Bat Pokémon', 'Supersonic', '—', 'Psychic', 'None', '1 Colorless', 57, 3, 6, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', 'None', '2 Colorless', 24, 3, 6, 2),
(90, 'Muk', 'Sludge Pokémon', 'Sludge', '30', 'Psychic', 'None', '2 Colorless', 13, 3, 5, 2),
(70, 'Grimer', 'Sludge Pokémon', 'Poison Gas', '10', 'Psychic', 'None', '1 Colorless', 48, 3, 5, 1),
(100, 'Ditto', 'Transform Pokémon', 'Transform', '—', 'Fighting', 'None', '1 Colorless', 18, 3, 7, 1),
(80, 'Hypno', 'Hypnosis Pokémon', 'Prophecy', '—', 'Psychic', 'None', '2 Colorless', 8, 3, 5, 2),
(70, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'None', '1 Colorless', 62, 1, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'None', '2 Colorless', 9, 1, 4, 2);
