-- 30 more Pokémon TCG cards
INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, ressistence, retreta, cardnumberincollection, collection_id, type_id, stage_id)
VALUES
(50, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '20', 'Psychic', 'None', '1 Colorless', 32, 1, 1, 1),
(70, 'Nidorina', 'Poison Pin Pokémon', 'Supersonic', '—', 'Psychic', 'None', '2 Colorless', 36, 1, 1, 2),
(90, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', 'None', '3 Colorless', 7, 1, 1, 3),
(60, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Attack', '10', 'Psychic', 'None', '1 Colorless', 55, 1, 1, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', 'None', '2 Colorless', 36, 1, 1, 2),
(100, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', 'None', '3 Colorless', 11, 1, 1, 3),
(40, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', 'None', '1 Colorless', 47, 1, 6, 1),
(60, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', 'None', '2 Colorless', 19, 1, 6, 2),
(50, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Lightning', 'None', '1 Colorless', 59, 1, 3, 1),
(70, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '—', 'Lightning', 'None', '2 Colorless', 39, 1, 3, 2),
(90, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Lightning', 'None', '3 Colorless', 13, 1, 3, 3),
(50, 'Ponyta', 'Fire Horse Pokémon', 'Smash Kick', '20', 'Water', 'None', '1 Colorless', 60, 1, 2, 1),
(80, 'Rapidash', 'Fire Horse Pokémon', 'Stomp', '20+', 'Water', 'None', '2 Colorless', 44, 1, 2, 2),
(90, 'Arcanine', 'Legendary Pokémon', 'Flamethrower', '50', 'Water', 'None', '3 Colorless', 23, 1, 2, 2),
(40, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'None', '1 Colorless', 61, 1, 7, 1),
(70, 'Raticate', 'Mouse Pokémon', 'Super Fang', '—', 'Fighting', 'None', '2 Colorless', 40, 1, 7, 2),
(50, 'Doduo', 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Lightning', 'None', '1 Colorless', 48, 1, 7, 1),
(80, 'Dodrio', 'Triple Bird Pokémon', 'Rage', '10+', 'Lightning', 'None', '2 Colorless', 34, 1, 7, 2),
(60, 'Farfetch’d', 'Wild Duck Pokémon', 'Leek Slap', '30', 'Lightning', 'None', '1 Colorless', 27, 1, 7, 1),
(70, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '20x', 'Fighting', 'Psychic', '3 Colorless', 5, 2, 7, 1),
(60, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', 'None', '1 Colorless', 58, 2, 1, 1),
(80, 'Parasect', 'Mushroom Pokémon', 'Spore', '—', 'Fire', 'None', '2 Colorless', 36, 2, 1, 2),
(70, 'Pinsir', 'Stag Beetle Pokémon', 'Iron Grip', '20', 'Fire', 'Fighting', '2 Colorless', 9, 2, 1, 1),
(60, 'Venonat', 'Insect Pokémon', 'Stun Spore', '10', 'Fire', 'None', '1 Colorless', 63, 2, 1, 1),
(80, 'Venomoth', 'Poison Moth Pokémon', 'Venom Powder', '10', 'Fire', 'None', '2 Colorless', 13, 2, 1, 2),
(70, 'Mankey', 'Pig Monkey Pokémon', 'Scratch', '20', 'Psychic', 'None', '1 Colorless', 56, 2, 6, 1),
(90, 'Primeape', 'Pig Monkey Pokémon', 'Fury Swipes', '20x', 'Psychic', 'None', '2 Colorless', 23, 2, 6, 2),
(80, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '—', 'Psychic', 'None', '1 Colorless', 7, 3, 6, 1),
(80, 'Hitmonchan', 'Punching Pokémon', 'Special Punch', '40', 'Psychic', 'None', '1 Colorless', 8, 3, 6, 1),
(100, 'Dragonite', 'Dragon Pokémon', 'Slam', '40x', 'Colorless', 'None', '2 Colorless', 4, 3, 7, 2);
